version: 2.1 # use CircleCI 2.1
jobs: # basic units of work in a run
  podman:
    executor: my-executor
    steps:
      - run:
          name: install podman
          command: |
            apt install podman
            podman version

executors:
  my-executor:
    machine:
      image: ubuntu-2004:current
    resource_class: medium

workflows:
  version: 2
  build-workflow:
    jobs:
      - podman
