version: 2.1 # use CircleCI 2.0
orbs:
    go: circleci/go@1.7.2
jobs: # basic units of work in a run
  podman-latest:
    executor: my-executor
    steps:
      - run:
          name: install podman
          command: |
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key \
              | gpg --dearmor \
              | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
                https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" \
              | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
            sudo apt-get update -qq
            sudo apt-get -qq -y install podman
            podman version

            # Starting systemd user service
            systemctl --user start podman.socket
            systemctl --user status podman.socket
  verify-go:
    executor: my-executor
    steps:
      - go/install:
          version: "1.19"
      - run:
          name: go version
          command: |
            go version

  push-master-images:
    docker:
      - image: circleci/golang:1.19
    parallelism: 1
    steps:
      - run:
          name: Push master images
          command: |
            echo "CircleCI playground"
            ls -l 
            pwd
            echo "this must only be executed for master branch only"
anchors:
  branch_filters: &run_for_master_branch
    filters:
      branches:
        ignore: /.*/
        only: /master/

executors:
  my-executor:
    machine:
      image: ubuntu-2004:current
    resource_class: medium

workflows:
  version: 2
  build-workflow:
    jobs:
      - podman-latest
      - verify-go
      - push-master-images:
          <<: *run_for_master_branch
          requires:
            - verify-go
