version: 2.1 # use CircleCI 2.0
orbs:
    go: circleci/go@1.7.2
jobs: # basic units of work in a run
  verify-go:
    executor: my-executor
    steps:
      - run:
          name: go version
          command: |
            go version

  push-master-images:
    docker:
      - image: circleci/golang:1.19
    parallelism: 1
    steps:
      - run:
          name: Push master images
          command: |
            echo "CircleCI playground"
            ls -l 
            pwd
            echo "this must only be executed for master branch only"
anchors:
  branch_filters: &run_for_master_branch
    filters:
      branches:
        ignore: /.*/
        only: /master/

executors:
  my-executor:
    machine:
      image: ubuntu-2004:current
    resource_class: small

workflows:
  version: 2
  build-workflow:
    jobs:
      - verify-go
      - build
      - push-master-images:
          <<: *run_for_master_branch
          requires:
            - build
