version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  podman:
    executor: my-executor
    steps:
      - run:
          name: install podman
          command: |
            apt install podman

executors:
  my-executor:
    machine:
      image: ubuntu-2004:2022.07.1
    resource_class: small

workflows:
  version: 2
  build-workflow:
    jobs:
      - podman
